seccomp.enabled: false

filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /root/suricata/logs/eve.json
  scan_frequency: 5s
  json.keys_under_root: true
  json.add_error_key: true
  tags: ["suricata"]
  fields:
    event.module: suricata
    event.dataset: suricata.eve
  fields_under_root: true

- type: log
  enabled: true
  paths:
    - /root/zeek/zeek-spool/manager/conn.log
    - /root/zeek/zeek-spool/manager/http.log
    - /root/zeek/zeek-spool/manager/capture_loss.log
  scan_frequency: 5s
  exclude_lines: ['^#']
  tags: ["zeek"]
  fields:
    event.module: zeek
  fields_under_root: true

output.elasticsearch:
  hosts: ["https://192.168.100.1:9200"]
  username: ${username}
  password: ${password}
  ssl.verification_mode: none
  indices:
  - index: "suricata"
    when.contains:
      tags: "suricata"
  - index: "zeek"
    when.contains:
      tags: "zeek"

setup.ilm.enabled: false
setup.template.name: "filebeat"
setup.template.pattern: "filebeat-*"
setup.template.json.enabled: true
setup.template.json.path: "/etc/filebeat/wazuh-template.json"
setup.template.json.name: "wazuh"
setup.template.overwrite: true

logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7